ScrollReveal().reveal('#home',{
    reset:true,
    delay:200,
});

ScrollReveal().reveal('.home_perfil_description',{
    reset:true,
    delay:500,
    origin:'bottom',
    distance:'100px'
});
ScrollReveal().reveal('.section-title',{
    reset:true,
    delay:300,
    origin:'bottom',
    distance:'100px'
});
ScrollReveal().reveal('img',{
    reset:true,
    delay:500,
});
ScrollReveal().reveal('.myDescription',{
    reset:true,
    delay:500,
});
ScrollReveal().reveal('.skill-card',{
    reset:true,
    delay:500,
    origin:'bottom',
    distance:'100px'
});
ScrollReveal().reveal('.service-card',{
    reset:true,
    delay:500,
    origin:'bottom',
    distance:'100px'
});
